sudo: required

services:
  - docker

script:
  - docker build -t hollowverse/build-env ./
  - docker build -t hollowverse/build-env:lambda ./ --file Dockerfile-lambda
  - docker build -t hollowverse/build-env:lambda-6 ./ --file Dockerfile-lambda-6
  - if [[ ($TRAVIS_PULL_REQUEST == "false") && ($TRAVIS_BRANCH == "master") ]]; then 
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" && \
      docker push hollowverse/build-env && \
      docker push hollowverse/build-env:lambda && \
      docker push hollowverse/build-env:lambda6;
    fi

notifications:
  email: false
