sudo: required

services:
  - docker

script:
  - docker build -t hollowverse/hollowverse-gae --file Dockerfile-gae ./
  - if [[ ($TRAVIS_PULL_REQUEST == "false") && ($TRAVIS_BRANCH == "master") ]]; then 
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" && docker push hollowverse/hollowverse-gae;
    fi

notifications:
  email: false
