sudo: required

services:
  - docker

script:
  - docker build --file Dockerfile-env ./
  - CONTAINER_ID=$(docker run -d -t) && docker commit $CONTAINER_ID hollowverse-gae
  - docker tag hollowverse-gae forabi/hollowverse-gae
  - docker push forabi/hollowverse-gae
