sudo: required

services:
  - docker

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t hollowverse/hollowverse-gae --file Dockerfile-gae ./
  - docker push hollowverse/hollowverse-gae

notifications:
  email: false
